In [1]:
import numpy as np
import pandas as pd

In [2]:
address='E:\\MY PYTHON\\Python Course Udemy\\falldeteciton.csv'
falls=pd.read_csv(address)
falls.head()

ACTIVITY     TIME        SL      EEG  BP   HR  CIRCLUATION
0         3  4722.92   4019.64 -1600.00  13   79          317
1         2  4059.12   2191.03 -1146.08  20   54          165
2         2  4773.56   2787.99 -1263.38  46   67          224
3         4  8271.27   9545.98 -2848.93  26  138          554
4         4  7102.16  14148.80 -2381.15  85  120          809

In [3]:
falls.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16382 entries, 0 to 16381
Data columns (total 7 columns):
ACTIVITY       16382 non-null int64
TIME           16382 non-null float64
SL             16382 non-null float64
EEG            16382 non-null float64
BP             16382 non-null int64
HR             16382 non-null int64
CIRCLUATION    16382 non-null int64
dtypes: float64(3), int64(4)
memory usage: 896.0 KB


In [4]:
falls.describe

<bound method NDFrame.describe of        ACTIVITY     TIME        SL      EEG  BP   HR  CIRCLUATION
0             3  4722.92   4019.64 -1600.00  13   79          317
1             2  4059.12   2191.03 -1146.08  20   54          165
2             2  4773.56   2787.99 -1263.38  46   67          224
3             4  8271.27   9545.98 -2848.93  26  138          554
4             4  7102.16  14148.80 -2381.15  85  120          809
...         ...      ...       ...      ...  ..  ...          ...
16377         4  9280.68  11417.00 -3021.64  36  156          654
16378         3  8479.69   9455.54 -2932.85  17  138          554
16379         2  8872.53  27449.90 -2870.00  33  156         1364
16380         4  7738.99  26466.40 -2920.24  97  156         1521
16381         3  9368.34  39149.10 -2970.00  21  196         1885

[16382 rows x 7 columns]>

In [5]:
falls.isnull()

ACTIVITY   TIME     SL    EEG     BP     HR  CIRCLUATION
0         False  False  False  False  False  False        False
1         False  False  False  False  False  False        False
2         False  False  False  False  False  False        False
3         False  False  False  False  False  False        False
4         False  False  False  False  False  False        False
...         ...    ...    ...    ...    ...    ...          ...
16377     False  False  False  False  False  False        False
16378     False  False  False  False  False  False        False
16379     False  False  False  False  False  False        False
16380     False  False  False  False  False  False        False
16381     False  False  False  False  False  False        False

[16382 rows x 7 columns]

In [6]:
falls.isnull().sum()

ACTIVITY       0
TIME           0
SL             0
EEG            0
BP             0
HR             0
CIRCLUATION    0
dtype: int64

In [7]:
import sklearn
from sklearn.preprocessing import scale
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn import preprocessing

In [8]:
falls.tail()

ACTIVITY     TIME        SL      EEG  BP   HR  CIRCLUATION
16377         4  9280.68  11417.00 -3021.64  36  156          654
16378         3  8479.69   9455.54 -2932.85  17  138          554
16379         2  8872.53  27449.90 -2870.00  33  156         1364
16380         4  7738.99  26466.40 -2920.24  97  156         1521
16381         3  9368.34  39149.10 -2970.00  21  196         1885

In [9]:
Xtrain=falls.drop(['HR'],axis=1)
Ytrain=falls['HR']

Xtest=falls.drop(['HR'],axis=1)
Ytest=falls['HR']

In [10]:
from sklearn.linear_model import LogisticRegression as LR1

In [11]:
log_reg=LR1()

In [12]:
log_reg.fit(Xtrain,Ytrain)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [13]:
y_predict=log_reg.predict(Xtest)

In [14]:
print(y_predict)

[ 72 580 580 ... 234 171 234]


In [15]:
print(type(y_predict))

<class 'numpy.ndarray'>


In [16]:
print(Ytest)

0         79
1         54
2         67
3        138
4        120
        ... 
16377    156
16378    138
16379    156
16380    156
16381    196
Name: HR, Length: 16382, dtype: int64


In [17]:
if len(Ytest)==len(y_predict) : print("Length compatible")

Length compatible


In [18]:
l1=list(Ytest)
l2=list(y_predict)

In [19]:
count=0
for m in range(len(l1)):
        if l1[m] == l2[m]:
            count += 1
            
print('matches=',count)
print('accuracy=',count*100/len(l1))

matches= 3029
accuracy= 18.489805884507387


In [20]:
from sklearn.metrics import classification_report, confusion_matrix

In [21]:
print(confusion_matrix(Ytest, y_predict))

[[275   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ...   1   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]


In [22]:
print(classification_report(Ytest,y_predict))

              precision    recall  f1-score   support

          33       1.00      1.00      1.00       275
          35       0.00      0.00      0.00         1
          40       0.00      0.00      0.00        55
          43       1.00      0.37      0.54        54
          46       0.00      0.00      0.00         1
          50       0.00      0.00      0.00         2
          51       0.34      0.10      0.15       151
          52       0.82      0.93      0.87       125
          53       0.00      0.00      0.00         6
          54       0.00      0.00      0.00       206
          55       0.00      0.00      0.00         3
          56       0.00      0.00      0.00         3
          57       0.00      0.00      0.00         2
          58       0.00      0.00      0.00         3
          59       0.00      0.00      0.00         4
          60       0.00      0.00      0.00         4
          61       0.00      0.00      0.00         4
          62       0.00    

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [23]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

In [24]:
fals=pd.read_csv('E:\\MY PYTHON\\Python Course Udemy\\falldeteciton.csv')
fals.head(7)

ACTIVITY     TIME        SL      EEG  BP   HR  CIRCLUATION
0         3  4722.92   4019.64 -1600.00  13   79          317
1         2  4059.12   2191.03 -1146.08  20   54          165
2         2  4773.56   2787.99 -1263.38  46   67          224
3         4  8271.27   9545.98 -2848.93  26  138          554
4         4  7102.16  14148.80 -2381.15  85  120          809
5         5  7015.24   7336.79 -1699.80  22   95          427
6         3  8620.28  24949.90 -3198.06  35  157         1519

In [25]:
fals.shape

(16382, 7)

In [26]:
fals.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16382 entries, 0 to 16381
Data columns (total 7 columns):
ACTIVITY       16382 non-null int64
TIME           16382 non-null float64
SL             16382 non-null float64
EEG            16382 non-null float64
BP             16382 non-null int64
HR             16382 non-null int64
CIRCLUATION    16382 non-null int64
dtypes: float64(3), int64(4)
memory usage: 896.0 KB


In [27]:
fals.describe

<bound method NDFrame.describe of        ACTIVITY     TIME        SL      EEG  BP   HR  CIRCLUATION
0             3  4722.92   4019.64 -1600.00  13   79          317
1             2  4059.12   2191.03 -1146.08  20   54          165
2             2  4773.56   2787.99 -1263.38  46   67          224
3             4  8271.27   9545.98 -2848.93  26  138          554
4             4  7102.16  14148.80 -2381.15  85  120          809
...         ...      ...       ...      ...  ..  ...          ...
16377         4  9280.68  11417.00 -3021.64  36  156          654
16378         3  8479.69   9455.54 -2932.85  17  138          554
16379         2  8872.53  27449.90 -2870.00  33  156         1364
16380         4  7738.99  26466.40 -2920.24  97  156         1521
16381         3  9368.34  39149.10 -2970.00  21  196         1885

[16382 rows x 7 columns]>

In [70]:
X=fals.iloc[:,[0,1,2,3,4,5]]
X

ACTIVITY     TIME        SL      EEG  BP   HR
0             3  4722.92   4019.64 -1600.00  13   79
1             2  4059.12   2191.03 -1146.08  20   54
2             2  4773.56   2787.99 -1263.38  46   67
3             4  8271.27   9545.98 -2848.93  26  138
4             4  7102.16  14148.80 -2381.15  85  120
...         ...      ...       ...      ...  ..  ...
16377         4  9280.68  11417.00 -3021.64  36  156
16378         3  8479.69   9455.54 -2932.85  17  138
16379         2  8872.53  27449.90 -2870.00  33  156
16380         4  7738.99  26466.40 -2920.24  97  156
16381         3  9368.34  39149.10 -2970.00  21  196

[16382 rows x 6 columns]

In [71]:
y=fals.iloc[:,6]
y

0         317
1         165
2         224
3         554
4         809
         ... 
16377     654
16378     554
16379    1364
16380    1521
16381    1885
Name: CIRCLUATION, Length: 16382, dtype: int64

In [72]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(X,y,test_size=0.2)

In [73]:
from sklearn.preprocessing import StandardScaler

scaler1=StandardScaler()
scaler1.fit(x_train)

x_train=scaler1.transform(x_train)
x_test=scaler1.transform(x_test)

In [74]:
x_train

array([[-1.35841543e+00, -5.09996123e-01, -3.79161414e-01,
         1.51838822e-03, -1.00114827e+00, -5.34938115e-01],
       [ 9.41217601e-01, -9.77423640e-01, -5.31115295e-01,
         7.21086737e-02, -8.97404425e-01, -1.00862633e+00],
       [-7.83507171e-01, -3.85718702e-01, -4.51051438e-01,
         1.47401506e-02, -4.82429055e-01, -2.21692683e-01],
       ...,
       [-7.83507171e-01, -1.58244597e+00, -5.83211339e-01,
         8.85940153e-02, -1.04264580e+00, -1.36771255e+00],
       [-1.35841543e+00,  6.37992014e-01,  1.22289038e+00,
        -4.01221123e-02, -5.20737884e-03,  1.04656931e+00],
       [-1.35841543e+00,  8.31641178e-01,  4.68324103e-01,
        -3.03444248e-02, -1.29699990e-01,  8.93766658e-01]])

In [75]:
x_test

array([[ 0.36630934, -0.70146319, -0.46917034,  0.04578601,  0.32677292,
        -0.59605917],
       [-0.78350717,  0.07712736, -0.05497081, -0.00461726,  1.84143302,
         0.26727579],
       [-1.35841543,  0.13809378, -0.17212005, -0.02203239, -0.31643891,
         0.33603699],
       ...,
       [ 0.9412176 , -0.28424843, -0.39347241,  0.09114384, -1.00114827,
        -0.35157494],
       [-1.35841543, -0.52234811, -0.44402274,  0.03651327, -0.60692167,
        -0.47381705],
       [-0.20859891,  0.15173424, -0.05481788, -0.00534507,  1.5924478 ,
         0.26727579]])

In [76]:
from sklearn.neighbors import KNeighborsClassifier
classifier1=KNeighborsClassifier(n_neighbors=18)
classifier1.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=18, p=2,
                     weights='uniform')

In [77]:
y_pred=classifier1.predict(x_test)

In [78]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[50  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
              precision    recall  f1-score   support

           5       0.98      1.00      0.99        50
          41       0.00      0.00      0.00         1
          45       0.00      0.00      0.00         1
          52       0.00      0.00      0.00         1
          63       0.00      0.00      0.00         0
          64       0.00      0.00      0.00         1
          65       0.00      0.00      0.00         0
          75       0.00      0.00      0.00         1
          77       0.00      0.00      0.00         0
          83       0.00      0.00      0.00         1
          87       0.00      0.00      0.00         1
          88       0.00      0.00      0.00         0
          90       0.00      0.00      0.00         1
         100       1.00      0.90      0.95        10
         101       0.00      0.00

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1439: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [79]:
error=[]

In [92]:
for i in range(1,25,2):
    knn=KNeighborsClassifier(n_neighbors=i)
    knn.fit(x_train,y_train)
    pred_i=knn.predict(x_test)
    error.append(np.mean(pred_i != y_test))
    #!= refers to not equal to.

In [93]:
error

[0.3384192859322551,
 0.35978028684772656,
 0.3692401586817211,
 0.3826670735428746,
 0.39060115959719255,
 0.40036618858712236,
 0.40341776014647546,
 0.41196216051266404,
 0.4171498321635642,
 0.42264266097039976,
 0.4293561184009765,
 0.4305767470247177,
 0.3384192859322551,
 0.363137015563015,
 0.3826670735428746,
 0.39548367409215746,
 0.40341776014647546,
 0.4153188892279524,
 0.42264266097039976,
 0.4299664327128471,
 0.43606957583155326,
 0.44461397619774184,
 0.450717119316448,
 0.4568202624351541,
 0.46200793408605434,
 0.46750076289288983,
 0.4748245346353372,
 0.48306377784559046,
 0.4891669209642966,
 0.4931339639914556,
 0.49862679279829114,
 0.5013732072017089,
 0.503509307293256,
 0.511443393347574,
 0.514494964906927,
 0.516325907842539,
 0.5233445224290509,
 0.526396093988404,
 0.5309734513274337,
 0.5352456515105279,
 0.5386023802258163,
 0.5407384803173635,
 0.5434848947207812,
 0.5483674092157461,
 0.5520292950869697,
 0.5587427525175466,
 0.5636252670125115,
 0.56

In [96]:
import matplotlib.pyplot as plt
plt.figure(figsize=(12,6))

<Figure size 864x432 with 0 Axes>

<Figure size 864x432 with 0 Axes>

In [101]:
print(knn.score(x_train,y_train))

0.5964135826020602


In [102]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame
import scipy
from scipy.stats import spearmanr
import matplotlib.pyplot as plt
from pylab import rcParams
import seaborn as sb

In [103]:

from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

In [104]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.20)

In [ ]:
svclassifier=SVC(kernel='linear')
svclassifier.fit(x_train,y_train)